defaults:
  - _self_
  - agent: drqv2
  - suite: dmc
  - override hydra/launcher: submitit_local

# Root Dir
root_dir: /path/to/root/dir/polytask
data_dir: /path/to/data/dir/

# replay buffer
replay_buffer_size: 30000
replay_buffer_num_workers: 2
nstep: 3
batch_size: 256
# misc
seed: 2
device: cuda
save_video: true
save_train_video: false
use_tb: true

# Description
description: 'Save buffers for distillation'

# Goal
goal_modality: 'pixels' # pixels, language, onehot
goal_dim: 512 # 384 - language, 512 - onehot, 512 - image

# Only distil a limited number of envs
num_envs_to_distil: 10

# experiment
obs_type: 'features' # pixels, features
experiment: save_buffer

train_encoder: false

# replay buffers
# replay_buffers: /path/to/buffers/
replay_buffers: ${data_dir}/buffers/
save_replay_buffers: ${data_dir}/buffers/${suite.name}

# model weights
weight_dir: ${data_dir}/weights/${suite.name}_${obs_type}
weight_name: rot

# Experiment logs
exp_group: ${now:%Y.%m.%d}_${suite.name}_distil_only_data
exp_name: ${now:%H%M%S}_${experiment}
hydra:
  run:
    dir: ./exp_local/${exp_group}/${exp_name}
  sweep:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}
    subdir: ${hydra.job.num}
  launcher:
    tasks_per_node: 1
    nodes: 1
    submitit_folder: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${experiment}/.slurm
