# @package agent
_target_: agent.distral.DistralAgent
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
device: ${device}
lr: 1e-4
critic_target_tau: 0.01
update_every_steps: 2
use_tb: ${use_tb}
num_expl_steps: 2000
hidden_dim: 1024
stddev_schedule: 'linear(1.0,0.1,1000000)'
stddev_clip: 0.3
obs_type: ${obs_type}
num_envs: ??? # to be specified later
