# @package agent
_target_: agent.progressive.DrQv2Agent
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
device: ${device}
lr: 1e-4
critic_target_tau: 0.01
update_every_steps: 2
use_tb: ${use_tb}
num_expl_steps: 2000
hidden_dim: 1024
stddev_schedule: 0.1 #${stddev_schedule_drq}
stddev_clip: 0.3
augment: True
obs_type: ${obs_type}
train_encoder: ${train_encoder}
rewards: sinkhorn_cosine
sinkhorn_rew_scale: 200
update_target_every: 10000
auto_rew_scale: True
auto_rew_scale_factor: 10
